# Secret values for local development (DO NOT COMMIT real values)
# Copy this file to app/.streamlit/secrets.toml (local only) and fill in values.
# Example:
# HF_TOKEN = "hf_xxx..."
# MODEL_SERVER_API_KEY = "your_api_key_here"
# OTHER_SEcrets = "..."

# Hint: keep secrets in platform environment variables or Render/Streamlit secrets.
